# Generated by Django 5.0.6 on 2024-08-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('wholesale', 'Wholesale')], default='personal', max_length=10),
        ),
    ]
