# Generated by Django 5.0.6 on 2024-06-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('abandoned', 'Abandoned'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
