# Generated by Django 5.0.6 on 2024-08-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentmetalprice',
            old_name='gold',
            new_name='gold_price',
        ),
        migrations.RenameField(
            model_name='currentmetalprice',
            old_name='palladium',
            new_name='palladium_price',
        ),
        migrations.RenameField(
            model_name='currentmetalprice',
            old_name='platinum',
            new_name='platinum_price',
        ),
        migrations.RenameField(
            model_name='currentmetalprice',
            old_name='rhodium',
            new_name='rhodium_price',
        ),
        migrations.RenameField(
            model_name='currentmetalprice',
            old_name='silver',
            new_name='silver_price',
        ),
    ]
