# Generated by Django 5.0.6 on 2024-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_gold_currentmetalprice_gold_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blurb', models.TextField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('weight', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('density', models.CharField(max_length=100)),
                ('melting_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='currentmetalprice',
            name='rhodium_price',
        ),
    ]
