# Generated by Django 5.0.6 on 2024-08-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutitem',
            old_name='quantity',
            new_name='weight',
        ),
    ]
