# Generated by Django 5.0.6 on 2024-08-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
